name: MiddleTasks
main: me.grenadinio.middletasks.Main
version: 1.0
commands:
  btp:
    description: Teleports you to golder or diamond block
    usage: /<command> gold|diamond
    permission: middletasksplugin.btp
  sethealth:
    description: Heals you
    usage: /<command> amount
    permission: middletaskplugin.sethealth
  showtext:
    description: Shows text on your screen
    usage: /<command> text1 text2
    permission: middletaskplugin.showtext
  gm:
    description: Gamemode
    usage: /<command> <0-3>
    permission: middletaskplugin.gm
  god:
    description: God mode
    usage: /<command>
    permission: middletaskplugin.god